### ISSUE TITLE
Фоновый режим / Автозапуск

### ISSUE THREAD

**Issue by INaffy** [wearvo/zapret-winws#2]
Есть ли возможность чтобы cmd'шка запускалась автоматом вместе с виндой и висела как служба? Пример как у GDPI

**Comment by wearvo** [comment]
> Есть ли возможность чтобы cmd'шка запускалась автоматом вместе с виндой и висела как служба? Пример как у GDPI
Пока что не добавлял. В скором времени сделаю.

**Comment by wearvo** [comment]
> Есть ли возможность чтобы cmd'шка запускалась автоматом вместе с виндой и висела как служба? Пример как у GDPI

Только что сделал, check readme.

**Comment by INaffy** [comment]
> > Есть ли возможность чтобы cmd'шка запускалась автоматом вместе с виндой и висела как служба? Пример как у GDPI
> 
> Только что сделал, check readme.

Пишет что не может найти winws.exe (если перекинуть все файлы из bin где основной cmd то запускается preset_discord)
! service_create.cmd не работает ни в какую

**Comment by wearvo** [comment]
> Пишет что не может найти winws.exe (если перекинуть все файлы из bin где основной cmd то запускается preset_discord) ! service_create.cmd не работает ни в какую

Увидел, сейчас поправлю

**Comment by wearvo** [comment]
> > Пишет что не может найти winws.exe (если перекинуть все файлы из bin где основной cmd то запускается preset_discord) ! service_create.cmd не работает ни в какую
> 
> Увидел, сейчас поправлю

Поправил, попробуй.

**Comment by INaffy** [comment]
> > > Пишет что не может найти winws.exe (если перекинуть все файлы из bin где основной cmd то запускается preset_discord) ! service_create.cmd не работает ни в какую
> > 
> > 
> > Увидел, сейчас поправлю
> 
> Поправил, попробуй.

Все работает, проверил оба варианта и перезагружал пк, молодец! Спасибо тебе <3

**Comment by wearvo** [comment]
> > > > Пишет что не может найти winws.exe (если перекинуть все файлы из bin где основной cmd то запускается preset_discord) ! service_create.cmd не работает ни в какую
> > > 
> > > 
> > > Увидел, сейчас поправлю
> > 
> > 
> > Поправил, попробуй.
> 
> Все работает, проверил оба варианта и перезагружал пк, молодец! Спасибо тебе <3
> 
> Кстати у меня работает и GDPI и твой скрипт, ничего не конфликтует (Ну тут кого как)

Не за что <3 Проверю с GDPI тоже, возможно пофиксилось пока все переписывал, спасибо)
